# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: The O Group
description: The O Group is an independent New York City creative agency focused on rethinking luxury. Advertising. Branding. Campaigns. Web Design. Strategy.
url: http://www.example.com

# CloudCannon uses these:
source: src
destination: dist
exclude:

header_logo: '/assets/images/header_logo.svg'

collections:
  projects:
    output: true
  authors:
    output: false

defaults:
  -
    scope:
      path: "cms.md"
    values:
      layout: "cms"
      permalink: "/cms/"
      _hide_content: true
  -
    scope:
      path: "agency.html"
    values:
      class: agency
      layout: default
      permalink: "/agency/"
  -
    scope:
      path: "work.html"
    values:
      class: work
      layout: default
      permalink: "/work/"
  -
    scope:
      path: "blog.html"
    values:
      class: blog
      layout: default
      permalink: "/blog/"
  -
    scope:
      path: "contact.html"
    values:
      class: contact
      layout: default
      permalink: "/contact/"
  -
    scope:
      path: ""
      type: "projects"
    values:
      class: project
      layout: project
      permalink: "/work/:slug/"
  -
    scope:
      type: posts
    values:
      layout: post
      class: blog
      permalink: "/blog/:title/"

# Extending Jekyll
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-redirect-from
  # - jekyll-polyglot
  - jekyll-paginate-v2
  # - jekyll-archives
  # - jekyll-feed

pagination:
  enabled: true
  per_page: 8
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'publish_date'
  sort_reverse: true
