# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: The O Group
description: A New York & Settle based creative agency focused on rethinking luxury.
url: https://www.ogroup.net
twitter: theogroup
social:
  links:
    - https://twitter.com/theogroup
    - https://www.facebook.com/theogroup
    - https://www.linkedin.com/company/the-o-group
logo: https://www.ogroup.net/assets/images/footer-logo.svg


# CloudCannon uses these:
source: src
destination: dist
exclude:

header_logo: '/assets/images/header_logo.svg'

collections:
  projects:
    output: true
  authors:
    output: false

defaults:
  -
    scope:
      path: "index.html"
    values:
      layout: default
      class: home
      permalink: "/"
  -
    scope:
      path: "work.html"
    values:
      class: work
      layout: default
      permalink: "/work/"
  -
    scope:
      path: "agency.html"
    values:
      class: agency
      layout: default
      permalink: "/agency/"
  -
    scope:
      path: "blog.html"
    values:
      class: blog
      layout: default
      permalink: "/blog/"
  -
    scope:
      path: "contact.html"
    values:
      class: contact
      layout: default
      permalink: "/contact/"
  -
    scope:
      path: "cms.md"
    values:
      layout: cms
      permalink: "/cms/"
      _hide_content: true
  -
    scope:
      path: ""
      type: "projects"
    values:
      class: project
      layout: project
      permalink: "/work/:slug/"
  -
    scope:
      type: posts
    values:
      layout: post
      class: blog
      permalink: "/blog/:title/"

_comments:
  image: The image used for FB/Twitter sharing

# Extending Jekyll
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll/tagging
  # - jekyll-redirect-from
  # - jekyll-polyglot
  - jekyll-paginate-v2
  # - jekyll-archives
  # - jekyll-feed

tag_page_layout: tag
tag_page_dir: blog/tags
tag_permalink_style: pretty

pagination:
  enabled: true
  per_page: 8
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'publish_date'
  sort_reverse: true
